### ISSUE TITLE
unifi-web-socket doesn't reconnect after UDM SE restart

### ISSUE THREAD

**Issue by Supergiovane** [NRCHKB/node-red-contrib-unifi-os#59]
Hi,
first of all, thank you a lot for this node. You saved me a lot of manual coding!
Node-Red 3.0.2
Node 16.4.2
Debian VM on Proxmox

**Issue**: unifi-web-socket doesn't reconnect after UDM SE restart. Stuck on Error code 4014

 <img width="297" alt="Node-RED___192_168_1_25" src="https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/37666636/448ef9fd-43c3-46bf-8020-dbf0ed77c8c1">

**To reproduce**: turn off the UDM SE, then turn it back on.

I've no log to show you, sorry!

**Comment by Shaquu** [comment]
Hello, seems like a standard case and would give my hand that it should work. Though, lets test it.. :) @crxporter @marcus-j-davies help please!

**Comment by marcus-j-davies** [comment]
I have not done any work on the web socket node.
BUT, if your use is for Protect - the Protect Node has recovery built in.

If your use is not for Protect, I'm not sure how the socket node behaves

**Comment by Supergiovane** [comment]
Hi Marcus
Thank you. 
I don’t use it for protect. 
I use it for wifi presence detection.

**Comment by crxporter** [comment]
I haven't noticed this problem in a while, things seem to come back nicely when I restart. 

Are you running the latest plug-in version? Which version of UniFi os is on the dream machine?

I'll be out of town until Wednesday but then I can run some tests on my stuff

**Comment by Supergiovane** [comment]
Hi
I’m not in hurry!
I’m on unifi network 7.4.162, console 3.1.13

**Comment by crxporter** [comment]
I've had some time to test this today - here is my experience:

I was watching the endpoint `/proxy/network/wss/s/default/events` on a websocket node. I updated from unifi os 3.1.12 to 3.1.14.

As the UDM-SE first shut down I got this status:
![screenshot 1](https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/38265886/18a3d37f-7e0c-495f-af84-668f483d731a)

Then within a few seconds of it being back online the error switched to:
![Screenshot 2](https://github.com/NRCHKB/node-red-contrib-unifi-os/assets/38265886/cfaa2252-98bd-4402-9ea4-9e90994d6e1c)

And within about 2 minutes I was back to "receiving data" like normal. It looks like it went to a 30-second retry loop as the console was booting.

Another thing I noticed is that the `/api/ws/system` endpoint recovered faster. This should be expected though because the UDM first boots itself then starts up network, protect, and other applications.

Versions:
nodered = 3.0.2
node-red-contrib-unifi-os = 0.9.0
unifi os = changed 3.1.12 to 3.1.14
unifi network = 7.5.165

Things have been smooth for restarts during the last few months if I remember right. I haven't had to manually fix anything for a while.

**Comment by Supergiovane** [comment]
Hi
Thanks for your efforts.
I've the same endpoint set `/proxy/network/wss/s/default/events`
I'll try again with unifi os 3.1.14, but with 3.1.13, my node never recovered from code 4014. I saw your codes are different.
In the meantime... thank you!

**Comment by Supergiovane** [comment]
Hi
I think so, because i was setting up a backup teltonika router, having exactly the same IP of the UDM SE.

**Comment by crxporter** [comment]
> exactly the same IP as the UDM SE

Ooh this is interesting. This could have triggered the failure to reconnect. The plugin probably tried connecting to the backup router but failed and decided "that's not a unifi thing"?

@Shaquu is there any explanation for this? A reason why the plugin would stop trying to reconnect after this type failure?

**Comment by Supergiovane** [comment]
Hi all
I'm closing this issue, after i've spent almost a day to try to reproduce again the issue, since update to unifi os 3.1.14, without success.
I'll monitor that anyway.
